###
GET http://localhost:5051/api/users/1

###
GET http://localhost:5051/api/family/

###
POST http://localhost:5051/api/users
Content-Type: application/json

{
  "name": "Wygon",
  "email": "test@example.com",
  "familyId" : null
}
###
GET  http://localhost:5051/api/users/2/family


###
POST http://localhost:5051/api/family/
Content-Type: application/json

{
  "name": "Kowalscy",
  "wage": 0
}
###
PUT http://localhost:5051/api/users/1
Content-Type: application/json

{
  "id": 1,
  "name": "Jan Kowalski",
  "email": "jan.kowalski@gmail.com",
  "familyId": 2
}

###
POST http://localhost:5051/api/transaction
Content-Type: application/json

{
  "type": "Dochód",
  "userId": 2,
  "value": 123
}

###
GET http://localhost:5051/api/users/3

###
GET http://localhost:5051/api/users/4/family

###
GET http://localhost:5051/api/family/2

###
GET http://localhost:5051/api/family/2/users

###

GET http://localhost:5051/api/family/5/users-with-transactions